"""Strategy signal generators for 5-second index option trading.

Each strategy file exports a `Strategy` class that inherits from `BaseStrategy`
and implements the `compute()` method to produce OptionSignals from spot, option,
and VIX DataFrames.

Strategies are auto-generated by scripts/auto_codegen_only.sh.
"""
